package moqtransport

import "sync"

// requestIDGenerator hands out this endpoint's Request IDs.
//
// draft-ietf-moq-transport-18 Section 10.1: a client generates even IDs from
// 0, a server odd IDs from 1, and each endpoint steps by 2. So the perspective
// alone fixes the sequence, and an ID arriving with the wrong parity for its
// sender closes the session with INVALID_REQUEST_ID.
//
// draft-17 deleted MAX_REQUEST_ID and REQUESTS_BLOCKED, so there is no ceiling
// to track any more: a peer that cannot accept another request refuses the
// bidirectional stream through QUIC's own flow control instead.
type requestIDGenerator struct {
	lock sync.Mutex
	next uint64
}

// newRequestIDGenerator returns the generator for p's side of the session.
func newRequestIDGenerator(p Perspective) *requestIDGenerator {
	first := uint64(0)
	if p == PerspectiveServer {
		first = 1
	}
	return &requestIDGenerator{next: first}
}

// nextID returns the next Request ID for a request this endpoint originates.
func (g *requestIDGenerator) nextID() uint64 {
	g.lock.Lock()
	defer g.lock.Unlock()
	id := g.next
	g.next += 2
	return id
}

// validPeerRequestID reports whether id could have been generated by the peer
// of an endpoint with perspective p. The parity is the whole test; ordering
// and duplicates are the caller's to track.
func validPeerRequestID(p Perspective, id uint64) bool {
	if p == PerspectiveServer {
		// Our peer is the client, which uses even IDs.
		return id%2 == 0
	}
	return id%2 == 1
}
