// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

import (
	"io"
)

func (m *FetchOk) appendV18(buf []byte) ([]byte, error) {
	var err error

	if m.EndOfTrack {
		buf = append(buf, 1)
	} else {
		buf = append(buf, 0)
	}
	buf = m.EndLocation.append(buf)
	buf, err = m.Parameters.appendNum(buf)
	if err != nil {
		return nil, err
	}
	buf = m.TrackProperties.appendDelta(buf)
	return buf, nil
}

func (m *FetchOk) parseV18(data []byte) error {
	var err error
	var n int

	if len(data) < 1 {
		return io.ErrUnexpectedEOF
	}
	if data[0] > 1 {
		return errInvalidBoolValue
	}
	m.EndOfTrack = data[0] == 1
	data = data[1:]

	n, err = m.EndLocation.parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	n, err = m.Parameters.parseNum(data)
	if err != nil {
		return err
	}
	data = data[n:]

	n, err = m.TrackProperties.parseAll(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
