// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"errors"
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

func (m *FetchOk) append_v15(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(m.RequestID))
	if m.EndOfTrack {
		buf = append(buf, byte(1))
	} else {
		buf = append(buf, byte(0))
	}
	buf = quicvarint.Append(buf, uint64(m.EndGroup))
	buf = quicvarint.Append(buf, uint64(m.EndObject))
	buf = quicvarint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = quicvarint.Append(buf, uint64(v.Type))
		if v.Type%2 == 0 {
			buf = quicvarint.Append(buf, uint64(v.Varint))
		} else {
			buf = quicvarint.Append(buf, uint64(len(v.Bytes)))
			buf = append(buf, v.Bytes...)
		}
	}
	return buf
}

func (m *FetchOk) parse_v15(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) < 1 {
		return io.ErrUnexpectedEOF
	}
	if data[0] > 1 {
		return errors.New("invalid bool flag value")
	}
	m.EndOfTrack = data[0] > 0
	data = data[1:]

	m.EndGroup, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.EndObject, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var numParameters uint64
	numParameters, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.Parameters = make([]KeyValuePair, numParameters)
	for i := range numParameters {
		typ, n, err := quicvarint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if typ%2 == 0 {
			val, n, err := quicvarint.Parse(data)
			if err != nil {
				return err
			}
			m.Parameters[i] = KeyValuePair{
				Type:   typ,
				Varint: val,
			}
			data = data[n:]
		} else {
			length, n, err := quicvarint.Parse(data)
			if err != nil {
				return err
			}
			data = data[n:]
			if len(data) < int(length) {
				return io.ErrUnexpectedEOF
			}
			m.Parameters[i] = KeyValuePair{
				Type:  typ,
				Bytes: data[:length],
			}
			data = data[length:]
		}
	}

	return nil
}
