// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

import (
	"github.com/Eyevinn/locmaf/vi64"
)

func (m *FetchHeader) appendV18(buf []byte) ([]byte, error) {
	buf = vi64.Append(buf, uint64(m.RequestID))
	return buf, nil
}

func (m *FetchHeader) parseV18(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
