// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/Eyevinn/locmaf/vi64"
)

func (m *GoAwayReq) appendV18(buf []byte) []byte {
	buf = vi64.Append(buf, uint64(len(m.NewSessionURI)))
	buf = append(buf, m.NewSessionURI...)
	buf = vi64.Append(buf, uint64(m.Timeout))
	return buf
}

func (m *GoAwayReq) parseV18(data []byte) error {
	var err error
	var n int

	var newSessionURILength uint64
	newSessionURILength, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]
	if newSessionURILength > 8192 {
		return errFieldTooLong
	}
	if uint64(len(data)) < newSessionURILength {
		return io.ErrUnexpectedEOF
	}
	m.NewSessionURI = string(data[:newSessionURILength])
	data = data[newSessionURILength:]

	m.Timeout, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
