// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

func (m *GoAway) append_v15(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(len(m.NewSessionURI)))
	buf = append(buf, []byte(m.NewSessionURI)...)
	return buf
}

func (m *GoAway) parse_v15(data []byte) error {
	var err error
	var n int

	var NewSessionURILength uint64
	NewSessionURILength, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) < int(NewSessionURILength) {
		return io.ErrUnexpectedEOF
	}
	m.NewSessionURI = string(data[:NewSessionURILength])
	data = data[NewSessionURILength:]

	return nil
}
