// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"github.com/quic-go/quic-go/quicvarint"
)

func (m *MaxRequestID) append_v15(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(m.MaxRequestID))
	return buf
}

func (m *MaxRequestID) parse_v15(data []byte) error {
	var err error
	var n int

	m.MaxRequestID, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	return nil
}
