// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/Eyevinn/locmaf/vi64"
)

func (m *Namespace) appendV18(buf []byte) ([]byte, error) {
	buf = vi64.Append(buf, uint64(len(m.TrackNamespaceSuffix)))
	for _, v := range m.TrackNamespaceSuffix {
		buf = vi64.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	return buf, nil
}

func (m *Namespace) parseV18(data []byte) error {
	var err error
	var n int

	var trackNamespaceSuffixCount uint64
	trackNamespaceSuffixCount, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]
	if trackNamespaceSuffixCount > 32 {
		return errTooManyFields
	}
	// The count cannot exceed the remaining bytes: every element costs at
	// least one byte, so this bounds the allocation without trusting it.
	if trackNamespaceSuffixCount > uint64(len(data)) {
		return io.ErrUnexpectedEOF
	}
	m.TrackNamespaceSuffix = make([][]byte, 0, trackNamespaceSuffixCount)
	for range trackNamespaceSuffixCount {
		var length uint64
		length, n, err = vi64.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]
		if uint64(len(data)) < length {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespaceSuffix = append(m.TrackNamespaceSuffix, data[:length])
		data = data[length:]
	}

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
