// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

func (m *Padding) appendV18(buf []byte) ([]byte, error) {
	return buf, nil
}

func (m *Padding) parseV18(data []byte) error {
	return nil
}
