// Code generated by "wiregen -draft 18 -decl messages_v18.go -dir ."; DO NOT EDIT.

package wire2

func (m *PublishOk) appendV18(buf []byte) ([]byte, error) {
	var err error

	buf, err = m.Parameters.appendNum(buf)
	if err != nil {
		return nil, err
	}
	buf = m.TrackProperties.appendDelta(buf)
	return buf, nil
}

func (m *PublishOk) parseV18(data []byte) error {
	var err error
	var n int

	n, err = m.Parameters.parseNum(data)
	if err != nil {
		return err
	}
	data = data[n:]

	n, err = m.TrackProperties.parseAll(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
