// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

func (m *PublishDone) append_v15(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(m.RequestID))
	buf = quicvarint.Append(buf, uint64(m.StatusCode))
	buf = quicvarint.Append(buf, uint64(m.StreamCount))
	buf = quicvarint.Append(buf, uint64(len(m.ErrorReason)))
	buf = append(buf, []byte(m.ErrorReason)...)
	return buf
}

func (m *PublishDone) parse_v15(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.StatusCode, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.StreamCount, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var ErrorReasonLength uint64
	ErrorReasonLength, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) < int(ErrorReasonLength) {
		return io.ErrUnexpectedEOF
	}
	m.ErrorReason = string(data[:ErrorReasonLength])
	data = data[ErrorReasonLength:]

	return nil
}
