// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/Eyevinn/locmaf/vi64"
)

func (m *PublishNamespace) appendV18(buf []byte) []byte {
	buf = vi64.Append(buf, uint64(m.RequestID))
	buf = vi64.Append(buf, uint64(len(m.TrackNamespace)))
	for _, v := range m.TrackNamespace {
		buf = vi64.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = m.Parameters.appendNum(buf)
	return buf
}

func (m *PublishNamespace) parseV18(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var trackNamespaceCount uint64
	trackNamespaceCount, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]
	if trackNamespaceCount > 32 {
		return errTooManyFields
	}
	// The count cannot exceed the remaining bytes: every element costs at
	// least one byte, so this bounds the allocation without trusting it.
	if trackNamespaceCount > uint64(len(data)) {
		return io.ErrUnexpectedEOF
	}
	m.TrackNamespace = make([][]byte, 0, trackNamespaceCount)
	for range trackNamespaceCount {
		var length uint64
		length, n, err = vi64.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]
		if uint64(len(data)) < length {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespace = append(m.TrackNamespace, data[:length])
		data = data[length:]
	}

	n, err = m.Parameters.parseNum(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
