// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

func (m *PublishNamespaceCancel) append_v15(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(len(m.TrackNamespace)))
	for _, v := range m.TrackNamespace {
		buf = quicvarint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = quicvarint.Append(buf, uint64(m.ErrorCode))
	buf = quicvarint.Append(buf, uint64(len(m.ErrorReason)))
	buf = append(buf, []byte(m.ErrorReason)...)
	return buf
}

func (m *PublishNamespaceCancel) parse_v15(data []byte) error {
	var err error
	var n int

	var numTrackNamespace uint64
	numTrackNamespace, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.TrackNamespace = make([][]byte, numTrackNamespace)
	for i := range numTrackNamespace {
		var length uint64
		length, n, err = quicvarint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if len(data) < int(length) {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespace[i] = data[:length]
		data = data[length:]
	}

	m.ErrorCode, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var ErrorReasonLength uint64
	ErrorReasonLength, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) < int(ErrorReasonLength) {
		return io.ErrUnexpectedEOF
	}
	m.ErrorReason = string(data[:ErrorReasonLength])
	data = data[ErrorReasonLength:]

	return nil
}
