// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

func (m *PublishOk) appendV18(buf []byte) []byte {
	buf = m.Parameters.appendNum(buf)
	buf = m.TrackProperties.appendDelta(buf)
	return buf
}

func (m *PublishOk) parseV18(data []byte) error {
	var err error
	var n int

	n, err = m.Parameters.parseNum(data)
	if err != nil {
		return err
	}
	data = data[n:]

	n, err = m.TrackProperties.parseAll(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
