// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/Eyevinn/locmaf/vi64"
)

func (m *RequestError) appendV18(buf []byte) []byte {
	buf = vi64.Append(buf, uint64(m.ErrorCode))
	buf = vi64.Append(buf, uint64(m.RetryInterval))
	buf = vi64.Append(buf, uint64(len(m.ErrorReason)))
	buf = append(buf, m.ErrorReason...)
	if m.Redirect != nil {
		buf = m.Redirect.append(buf)
	}
	return buf
}

func (m *RequestError) parseV18(data []byte) error {
	var err error
	var n int

	m.ErrorCode, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.RetryInterval, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var errorReasonLength uint64
	errorReasonLength, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]
	if errorReasonLength > 1024 {
		return errFieldTooLong
	}
	if uint64(len(data)) < errorReasonLength {
		return io.ErrUnexpectedEOF
	}
	m.ErrorReason = string(data[:errorReasonLength])
	data = data[errorReasonLength:]

	if len(data) > 0 {
		m.Redirect = &Redirect{}
		n, err = m.Redirect.parse(data)
		if err != nil {
			return err
		}
		data = data[n:]
	}

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
