// Code generated by "wiregen -draft 18 -decl messages_v18.go -dir ."; DO NOT EDIT.

package wire2

import (
	"github.com/Eyevinn/locmaf/vi64"
)

func (m *RequestUpdate) appendV18(buf []byte) ([]byte, error) {
	var err error

	buf = vi64.Append(buf, uint64(m.RequestID))
	buf, err = m.Parameters.appendNum(buf)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func (m *RequestUpdate) parseV18(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	n, err = m.Parameters.parseNum(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
