// Code generated by "wiregen -draft 18 -dir . -pkg wire2"; DO NOT EDIT.

package wire2

func (m *Setup) appendV18(buf []byte) []byte {
	buf = m.Options.appendDelta(buf)
	return buf
}

func (m *Setup) parseV18(data []byte) error {
	var err error
	var n int

	n, err = m.Options.parseAll(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
