// Code generated by "wiregen -draft 18 -decl messages_v18.go -dir ."; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/Eyevinn/locmaf/vi64"
)

func (m *TrackStatus) appendV18(buf []byte) ([]byte, error) {
	var err error

	buf = vi64.Append(buf, uint64(m.RequestID))
	buf = vi64.Append(buf, uint64(len(m.TrackNamespace)))
	for _, v := range m.TrackNamespace {
		buf = vi64.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = vi64.Append(buf, uint64(len(m.TrackName)))
	buf = append(buf, m.TrackName...)
	buf, err = m.Parameters.appendNum(buf)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func (m *TrackStatus) parseV18(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var trackNamespaceCount uint64
	trackNamespaceCount, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]
	if trackNamespaceCount > 32 {
		return errTooManyFields
	}
	// The count cannot exceed the remaining bytes: every element costs at
	// least one byte, so this bounds the allocation without trusting it.
	if trackNamespaceCount > uint64(len(data)) {
		return io.ErrUnexpectedEOF
	}
	m.TrackNamespace = make([][]byte, 0, trackNamespaceCount)
	for range trackNamespaceCount {
		var length uint64
		length, n, err = vi64.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]
		if uint64(len(data)) < length {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespace = append(m.TrackNamespace, data[:length])
		data = data[length:]
	}

	var trackNameLength uint64
	trackNameLength, n, err = vi64.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]
	if uint64(len(data)) < trackNameLength {
		return io.ErrUnexpectedEOF
	}
	m.TrackName = data[:trackNameLength]
	data = data[trackNameLength:]

	n, err = m.Parameters.parseNum(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) > 0 {
		return errTrailingBytes
	}
	return nil
}
